from typing import Protocol
import asyncio


class AudioTranscriber(Protocol):
    def __init__(self) -> None: ...

    async def send_audio(self, audio_queue: asyncio.Queue) -> None: ...

    # async def push_audio_to_queue(
    #     self, audio_data_websocket: WebSocket, audio_queue: asyncio.Queue
    # ) -> None: ...

    async def start_transcribing(self, audio_queue: asyncio.Queue) -> None: ...

    async def stop_recording(self) -> None: ...

    def start_recording(self) -> None: ...

    @property
    def is_recording(self) -> bool: ...