"""audio_uploads

Revision ID: 06e4c03101a0
Revises: 7b6e0da8492c
Create Date: 2025-09-06 22:18:32.979525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e4c03101a0'
down_revision: Union[str, None] = '7b6e0da8492c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_uploads', sa.Column('content_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_uploads', 'content_type')
    # ### end Alembic commands ###
