"""updated_image_uploads

Revision ID: 75cc7b1de854
Revises: a797fb49ad3a
Create Date: 2025-07-17 03:04:43.415578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75cc7b1de854'
down_revision: Union[str, None] = 'a797fb49ad3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_uploads', sa.Column('lab_report_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'image_uploads', 'lab_reports', ['lab_report_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_uploads', type_='foreignkey')
    op.drop_column('image_uploads', 'lab_report_id')
    # ### end Alembic commands ###
