"""doctor-reports

Revision ID: 7b6e0da8492c
Revises: 75cc7b1de854
Create Date: 2025-08-20 10:41:03.749979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6e0da8492c'
down_revision: Union[str, None] = '75cc7b1de854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_reports', 'audio_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor_reports', 'audio_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
