"""org_setup

Revision ID: 8b15c220b7ff
Revises: 06e4c03101a0
Create Date: 2025-10-16 02:57:32.966431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b15c220b7ff'
down_revision: Union[str, None] = '06e4c03101a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('credit_usage_type', sa.Enum('pool', 'role', 'individual', name='creditusagetype'), nullable=False),
    sa.Column('connection_access', sa.Enum('all', 'restricted', 'multiple', name='connectionaccesstype'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('profile_picture_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_picture_id'], ['image_uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('invitation_status', sa.Enum('pending', 'accepted', 'rejected', 'cancelled', 'expired', name='invitationsstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_invitation_status'), 'organization_invitations', ['invitation_status'], unique=False)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_user_email'), 'organization_invitations', ['user_email'], unique=False)
    op.add_column('image_uploads', sa.Column('org_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'image_uploads', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])

    # Add timestamps to users table
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), index=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now(), index=True))

# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'image_uploads', type_='foreignkey')
    op.drop_index(op.f('ix_organization_invitations_user_email'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_invitation_status'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_table('organizations')

    # Remove timestamps from users table
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')

# ### end Alembic commands ###
