"""init

Revision ID: c0f797302a11
Revises:
Create Date: 2025-07-17 01:22:40.188440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c0f797302a11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkpoint_blobs',
                    sa.Column('thread_id', sa.String(), nullable=False),
                    sa.Column('checkpoint_ns', sa.String(), server_default='', nullable=False),
                    sa.Column('channel', sa.String(), nullable=False),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('blob', sa.LargeBinary(), nullable=True),
                    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version')
                    )
    op.create_table('checkpoint_migrations',
                    sa.Column('v', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('v')
                    )
    op.create_table('checkpoint_writes',
                    sa.Column('thread_id', sa.String(), nullable=False),
                    sa.Column('checkpoint_ns', sa.String(), server_default='', nullable=False),
                    sa.Column('checkpoint_id', sa.String(), nullable=False),
                    sa.Column('task_id', sa.String(), nullable=False),
                    sa.Column('idx', sa.Integer(), nullable=False),
                    sa.Column('channel', sa.String(), nullable=False),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('blob', sa.LargeBinary(), nullable=False),
                    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
                    )
    op.create_table('checkpoints',
                    sa.Column('thread_id', sa.String(), nullable=False),
                    sa.Column('checkpoint_ns', sa.String(), server_default='', nullable=False),
                    sa.Column('checkpoint_id', sa.String(), nullable=False),
                    sa.Column('parent_checkpoint_id', sa.String(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
                    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
                    )
    op.create_table('credit_constants',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('route', sa.String(), nullable=False),
                    sa.Column('required_credit', sa.Float(), nullable=False),
                    sa.Column('input_rates', sa.Float(), nullable=False),
                    sa.Column('output_rates', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('password_reset_tokens',
                    sa.Column('token', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('token')
                    )
    op.create_index(op.f('ix_password_reset_tokens_email'), 'password_reset_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_table('plans',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('plan_type', sa.Enum('regular', 'standard', 'premium', name='plan_type_enum'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('plan_type')
                    )
    op.create_table('users',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('auth_id', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('credits', sa.Float(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('profile_picture_url', sa.String(), nullable=True),
                    sa.Column('role', sa.String(), nullable=True),
                    sa.Column('logged_in', sa.Boolean(), nullable=True),
                    sa.Column('free_trial', sa.Boolean(), nullable=True),
                    sa.Column('user_code', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_table('audio_uploads',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('filename', sa.String(), nullable=False),
                    sa.Column('audio', sa.LargeBinary(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('user_id', 'filename')
                    )
    op.create_table('chat_session',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('session_id', sa.String(), nullable=False),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('session_id')
                    )
    op.create_table('chief_complaint',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('presenting_complaints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('hpc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('additional_info', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('doctor_dashboard_diagnoses',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('summary', sa.String(), nullable=True),
                    sa.Column('differential_diagnosis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('alternative_diagnoses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('primary_index', sa.Integer(), nullable=True),
                    sa.Column('clinical_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('doctor_id', sa.UUID(), nullable=True),
                    sa.Column('patient_id', sa.UUID(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_doctor_dashboard_diagnoses_id'), 'doctor_dashboard_diagnoses', ['id'], unique=False)
    op.create_table('drug_history_and_allergies',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('medicines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('therapies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('upset_medicines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('additional_info', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('family_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('family_members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('hereditary_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('additional_info', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('medical_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('general', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('medical', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('surgical', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('obstetric_gynecological', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('additional_info', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('payments',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('reference', sa.String(), nullable=True),
                    sa.Column('transaction', sa.String(), nullable=True),
                    sa.Column('trxref', sa.String(), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('plan_type', sa.Enum('regular', 'standard', 'premium', name='plan_type_enum'), nullable=True),
                    sa.ForeignKeyConstraint(['plan_type'], ['plans.plan_type'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('personal_information',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('firstname', sa.String(), nullable=False),
                    sa.Column('lastname', sa.String(), nullable=False),
                    sa.Column('nickname', sa.String(), nullable=True),
                    sa.Column('gender', postgresql.ENUM('Male', 'Female', 'Rather not say', name='gender'), nullable=False),
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('date_of_birth', sa.Date(), nullable=False),
                    sa.Column('date_of_admission', sa.Date(), nullable=True),
                    sa.Column('additional_info', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('social_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=True),
                    sa.Column('marital_status', postgresql.ENUM('Single', 'Married', 'Divorced', 'Separated', 'Widowed', 'Rather not say', name='marital_status'), nullable=True),
                    sa.Column('partner_health', sa.String(), nullable=True),
                    sa.Column('number_of_children', sa.Integer(), nullable=True),
                    sa.Column('children_health', sa.String(), nullable=True),
                    sa.Column('occupation', sa.String(), nullable=True),
                    sa.Column('financial_worries', postgresql.ENUM('Yes', 'No', name='financial_worries'), nullable=True),
                    sa.Column('smoking_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('alcohol_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('travel_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('pets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('additional_info', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('systemic_enquiry',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('respiratory_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('chest_issues', postgresql.ENUM('Yes', 'No', name='chest_issues'), nullable=True),
                    sa.Column('appetite_weight_changes', postgresql.ENUM('Yes', 'No', name='appetite_weight_changes'), nullable=True),
                    sa.Column('gastrointestinal_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('urinary_issues', sa.String(), nullable=True),
                    sa.Column('sexual_health', sa.String(), nullable=True),
                    sa.Column('musculoskeletal_issues', sa.String(), nullable=True),
                    sa.Column('neurological_symptoms', sa.String(), nullable=True),
                    sa.Column('psychological_symptoms', sa.String(), nullable=True),
                    sa.Column('additional_info', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('thread_ids',
                    sa.Column('thread_id', sa.String(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('thread_id', 'patient_id')
                    )
    op.create_table('user_connections',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('connection_status', postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='requeststatusenum'), nullable=True),
                    sa.Column('sender_id', sa.UUID(), nullable=False),
                    sa.Column('receiver_user_code', sa.String(), nullable=False),
                    sa.Column('receiver_id', sa.UUID(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_user_connections_id'), 'user_connections', ['id'], unique=False)
    op.create_table('billing_history',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('status', sa.Enum('processing', 'success', 'failed', name='statusenum'), nullable=True),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('credits', sa.Float(), nullable=True),
                    sa.Column('payment_id', sa.UUID(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('plan', sa.String(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chat_message',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('session_id', sa.String(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('message', sa.Text(), nullable=True),
                    sa.Column('type', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['session_id'], ['chat_session.session_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('doctor_reports',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('doctor_id', sa.UUID(), nullable=False),
                    sa.Column('patient_id', sa.UUID(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('audio_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.Enum('progress_note', 'operative_note', 'admission_note', 'discharge_summary', 'procedure_note', 'referral_note', 'death_note', 'physical_examination', 'history_taking', name='reporttype'), nullable=False),
                    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['audio_id'], ['audio_uploads.id'], ),
                    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_doctor_reports_type'), 'doctor_reports', ['type'], unique=False)
    op.create_table('processing_jobs',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('upload_id', sa.UUID(), nullable=False),
                    sa.Column('task', sa.Enum('transcribe', 'translate', name='task'), nullable=False),
                    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='status'), nullable=False),
                    sa.Column('result', sa.JSON(), nullable=True),
                    sa.Column('clean_transcript', sa.String(), nullable=True),
                    sa.Column('error', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['upload_id'], ['audio_uploads.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reports',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('job_id', sa.UUID(), nullable=False),
                    sa.Column('content', sa.JSON(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_doctor_reports_type'), table_name='doctor_reports')
    op.drop_table('doctor_reports')
    op.drop_table('chat_message')
    op.drop_table('billing_history')
    op.drop_index(op.f('ix_user_connections_id'), table_name='user_connections')
    op.drop_table('user_connections')
    op.drop_table('thread_ids')
    op.drop_table('systemic_enquiry')
    op.drop_table('social_history')
    op.drop_table('personal_information')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('medical_history')
    op.drop_table('family_history')
    op.drop_table('drug_history_and_allergies')
    op.drop_index(op.f('ix_doctor_dashboard_diagnoses_id'), table_name='doctor_dashboard_diagnoses')
    op.drop_table('doctor_dashboard_diagnoses')
    op.drop_table('chief_complaint')
    op.drop_table('chat_session')
    op.drop_table('audio_uploads')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plans')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_email'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('credit_constants')
    op.drop_table('checkpoints')
    op.drop_table('checkpoint_writes')
    op.drop_table('checkpoint_migrations')
    op.drop_table('checkpoint_blobs')
    # ### end Alembic commands ###
